version: "3.8"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:  
      - .env  # This ensures your .env file is loaded inside the container
    environment:
      - KAGGLE_USERNAME=${KAGGLE_USERNAME}
      - KAGGLE_KEY=${KAGGLE_KEY}  
    volumes:
      - .:/app
